name: 'a11yGuard'
description: 'Detect accessibility regressions between your PR and main'
author: 'a11y-diff'

branding:
  icon: 'users'
  color: 'purple'

inputs:
  OPENROUTER_API_KEY:
    description: 'API Key for OpenRouter (required for AI fixes)'
    required: false
    default: ''

  APP_DIR:
    description: 'Path to your app directory relative to the repo root (e.g. "my-app", "frontend", or "." for root).'
    required: false
    default: '.'

  BUILD_DIR:
    description: 'The static build output directory name (e.g. "out", "dist", "build").'
    required: false
    default: 'dist'

  BUILD_COMMAND:
    description: 'The npm script used to build your app.'
    required: false
    default: 'build'

  URLS:
    description: 'Comma-separated list of URL paths to scan (e.g. "/,/about,/dashboard").'
    required: false
    default: '/'

  IGNORE_RULES:
    description: 'Comma-separated list of axe rule IDs to ignore (e.g. "color-contrast,duplicate-id").'
    required: false
    default: ''

  FAIL_ON_REGRESSION:
    description: 'Fail the check if new violations are introduced. Set to "false" to report only.'
    required: false
    default: 'true'

  IMPACT_LEVEL:
    description: 'Minimum impact level to track. One of: minor, moderate, serious, critical.'
    required: false
    default: 'moderate'

  WAIT_FOR_NETWORK_IDLE:
    description: 'Wait for network idle before scanning each page. Recommended for SPAs.'
    required: false
    default: 'true'

  EXTRA_WAIT_MS:
    description: 'Additional wait time in milliseconds after page load before scanning.'
    required: false
    default: '500'

  TOKEN:
    description: 'GitHub token with pull-requests: write permission.'
    required: false
    default: ${{ github.token }}

  BASE_URL:
    description: 'Base branch deployment URL (e.g. production or main preview). If set with PR_URL, skips local build/serve.'
    required: false
    default: ''
    
  PR_URL:
    description: 'PR preview deployment URL (e.g. Vercel PR comment link). If set with BASE_URL, skips local build/serve.'
    required: false
    default: ''

outputs:
  new_violations:
    description: 'Number of new violations introduced by this PR.'
  resolved_violations:
    description: 'Number of violations resolved by this PR.'
  regression:
    description: 'Whether a regression was detected ("true" or "false").'

runs:
  using: 'composite'
  steps:

    # 1. Checkout PR branch (skip when using BASE_URL + PR_URL)
    - name: Checkout PR branch
      if: inputs.BASE_URL == '' || inputs.PR_URL == ''
      uses: actions/checkout@v4
      with:
        path: _a11y_pr

    # 2. Checkout base (main) branch (skip when using BASE_URL + PR_URL)
    - name: Checkout base branch
      if: inputs.BASE_URL == '' || inputs.PR_URL == ''
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.base.sha }}
        path: _a11y_base

    # 3. Setup Node
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20

    # 4. Install action's own dependencies
    - name: Install action dependencies
      shell: bash
      run: |
        cd ${{ github.action_path }}
        npm ci

    # 5. Install Playwright browser
    - name: Install Playwright browser
      shell: bash
      run: |
        cd ${{ github.action_path }}
        npx playwright install chromium --with-deps

    # 6. Install & build PR branch (skip when using BASE_URL + PR_URL)
    - name: Install dependencies (PR branch)
      if: inputs.BASE_URL == '' || inputs.PR_URL == ''
      shell: bash
      run: |
        cd _a11y_pr/${{ inputs.APP_DIR }}
        npm ci

    - name: Build PR branch
      if: inputs.BASE_URL == '' || inputs.PR_URL == ''
      shell: bash
      run: |
        cd _a11y_pr/${{ inputs.APP_DIR }}
        rm -rf ${{ inputs.BUILD_DIR }} .next
        npm run ${{ inputs.BUILD_COMMAND }}

    # 7. Install & build base branch (skip when using BASE_URL + PR_URL)
    - name: Install dependencies (base branch)
      if: inputs.BASE_URL == '' || inputs.PR_URL == ''
      shell: bash
      run: |
        cd _a11y_base/${{ inputs.APP_DIR }}
        npm ci

    - name: Build base branch
      if: inputs.BASE_URL == '' || inputs.PR_URL == ''
      shell: bash
      run: |
        cd _a11y_base/${{ inputs.APP_DIR }}
        rm -rf ${{ inputs.BUILD_DIR }} .next
        npm run ${{ inputs.BUILD_COMMAND }}

    - name: Debug HTML diff
      if: inputs.BASE_URL == '' || inputs.PR_URL == ''
      shell: bash
      run: |
        echo "=== Checking if index.html differs between branches ==="
        diff _a11y_base/${{ inputs.APP_DIR }}/${{ inputs.BUILD_DIR }}/index.html \
             _a11y_pr/${{ inputs.APP_DIR }}/${{ inputs.BUILD_DIR }}/index.html \
          && echo "FILES ARE IDENTICAL" || echo "FILES DIFFER"

    # 8. Serve both builds (skip when using BASE_URL + PR_URL)
    - name: Serve both builds
      if: inputs.BASE_URL == '' || inputs.PR_URL == ''
      shell: bash
      run: |
        export PATH="${{ github.action_path }}/node_modules/.bin:$PATH"
        BASE_DIR="_a11y_base/${{ inputs.APP_DIR }}/${{ inputs.BUILD_DIR }}"
        PR_DIR="_a11y_pr/${{ inputs.APP_DIR }}/${{ inputs.BUILD_DIR }}"

        serve "$BASE_DIR" -l 4000 > /tmp/serve-4000.log 2>&1 &
        serve "$PR_DIR" -l 5000 > /tmp/serve-5000.log 2>&1 &

        echo "Waiting for servers to bind..."
        wait-on tcp:127.0.0.1:4000 --timeout 60000 \
          || (echo "Base branch server failed:" && cat /tmp/serve-4000.log && exit 1)
        wait-on tcp:127.0.0.1:5000 --timeout 60000 \
          || (echo "PR branch server failed:" && cat /tmp/serve-5000.log && exit 1)

        echo "Both servers ready."

    # 9. Scan base branch (BASE_URL or localhost:4000)
    - name: Scan base branch
      shell: bash
      run: |
        node ${{ github.action_path }}/src/scan.js \
          --baseUrl "${{ inputs.BASE_URL || 'http://localhost:4000' }}" \
          --output /tmp/a11y_baseline.json \
          --urls "${{ inputs.URLS }}" \
          --ignore "${{ inputs.IGNORE_RULES }}" \
          --impactLevel "${{ inputs.IMPACT_LEVEL }}" \
          --waitForNetworkIdle "${{ inputs.WAIT_FOR_NETWORK_IDLE }}" \
          --extraWaitMs "${{ inputs.EXTRA_WAIT_MS }}"

    # 10. Scan PR branch (PR_URL or localhost:5000)
    - name: Scan PR branch
      shell: bash
      run: |
        node ${{ github.action_path }}/src/scan.js \
          --baseUrl "${{ inputs.PR_URL || 'http://localhost:5000' }}" \
          --output /tmp/a11y_pr.json \
          --urls "${{ inputs.URLS }}" \
          --ignore "${{ inputs.IGNORE_RULES }}" \
          --impactLevel "${{ inputs.IMPACT_LEVEL }}" \
          --waitForNetworkIdle "${{ inputs.WAIT_FOR_NETWORK_IDLE }}" \
          --extraWaitMs "${{ inputs.EXTRA_WAIT_MS }}"

    # 11. Diff results & Set Output
    - name: Diff accessibility results
      id: diff_step
      shell: bash
      run: |
        set +e
        node ${{ github.action_path }}/src/diff.js \
          --baseline /tmp/a11y_baseline.json \
          --head /tmp/a11y_pr.json \
          --output /tmp/a11y_diff.json
        EXIT=$?
        set -e
        if [ $EXIT -eq 1 ]; then echo "HAS_REGRESSION=true" >> $GITHUB_ENV; fi
        exit 0

    # 12. Post PR comment
    - name: Post PR comment
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.TOKEN }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        FAIL_ON_REGRESSION: ${{ inputs.FAIL_ON_REGRESSION }}
      run: |
        set +e
        node ${{ github.action_path }}/src/comment.js --diff /tmp/a11y_diff.json
        set -e

    # 13. Run AI Auto-Fixer
    - name: Run AI Auto-Fixer
      if: env.HAS_REGRESSION == 'true'
      shell: bash
      env:
        OPENROUTER_API_KEY: ${{ inputs.OPENROUTER_API_KEY }}
        GITHUB_TOKEN: ${{ inputs.TOKEN }}
        PR_PROJECT_PATH: "_a11y_pr"
        PR_NUMBER: ${{ github.event.pull_request.number }}
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: |
        node ${{ github.action_path }}/src/auto-fix.js --diff /tmp/a11y_diff.json

    # 14. Commit and Push AI Fixes
    - name: Commit and Push AI Fixes
      if: env.HAS_REGRESSION == 'true'
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "a11yGuard BOT: Auto-fix accessibility violations"
        commit_user_name: "a11yGuard-bot[bot]"
        commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
        commit_author: "a11yGuard-bot <41898282+github-actions[bot]@users.noreply.github.com>"
        repository: _a11y_pr
        branch: ${{ github.head_ref }}
        file_pattern: '. src/app/skills/page.tsx'


    # 15. Upload scan artifacts
    - name: Upload scan artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: a11y-diff-results
        path: |
          /tmp/a11y_baseline.json
          /tmp/a11y_pr.json
          /tmp/a11y_diff.json
        retention-days: 7

    # 16. Fail the check if regression
    - name: Fail check if regression
      if: env.HAS_REGRESSION == 'true' && inputs.FAIL_ON_REGRESSION == 'true'
      shell: bash
      run: |
        echo "Accessibility regression(s) were detected. The check fails."
        echo "If the AI auto-fixer ran, it may have pushed fixes — re-run the check to verify."
        exit 1
