name: 'A11y Diff'
description: 'Detect accessibility regressions between your PR and main. Fails the check if violations increase — without punishing existing debt.'
author: 'a11y-diff'

branding:
  icon: 'eye'
  color: 'blue'

inputs:
  APP_DIR:
    description: 'Path to your app directory relative to the repo root (e.g. "my-app", "frontend", or "." for root).'
    required: false
    default: '.'

  BUILD_DIR:
    description: 'The static build output directory name (e.g. "out", "dist", "build").'
    required: false
    default: 'dist'

  BUILD_COMMAND:
    description: 'The npm script used to build your app.'
    required: false
    default: 'build'

  URLS:
    description: 'Comma-separated list of URL paths to scan (e.g. "/,/about,/dashboard").'
    required: false
    default: '/'

  IGNORE_RULES:
    description: 'Comma-separated list of axe rule IDs to ignore (e.g. "color-contrast,duplicate-id").'
    required: false
    default: ''

  FAIL_ON_REGRESSION:
    description: 'Fail the check if new violations are introduced. Set to "false" to report only.'
    required: false
    default: 'true'

  IMPACT_LEVEL:
    description: 'Minimum impact level to track. One of: minor, moderate, serious, critical.'
    required: false
    default: 'moderate'

  WAIT_FOR_NETWORK_IDLE:
    description: 'Wait for network idle before scanning each page. Recommended for SPAs.'
    required: false
    default: 'true'

  EXTRA_WAIT_MS:
    description: 'Additional wait time in milliseconds after page load before scanning.'
    required: false
    default: '500'

  TOKEN:
    description: 'GitHub token with pull-requests: write permission.'
    required: false
    default: ${{ github.token }}

outputs:
  new_violations:
    description: 'Number of new violations introduced by this PR.'
  resolved_violations:
    description: 'Number of violations resolved by this PR.'
  regression:
    description: 'Whether a regression was detected ("true" or "false").'

runs:
  using: 'composite'
  steps:
    - name: Debug action version
      shell: bash
      run: |
        echo "=== action.yml header ==="
        head -5 ${{ github.action_path }}/action.yml
        echo "=== scan.js first line ==="
        head -3 ${{ github.action_path }}/src/scan.js
        echo "=== comment.js first line ==="
        head -3 ${{ github.action_path }}/src/comment.js
        echo "=== package.json ==="
        cat ${{ github.action_path }}/package.json
  
    - name: Debug build contents
      shell: bash
      run: |
        echo "=== Base branch index.html ===" 
        cat _a11y_base/out/index.html | grep -i "button\|img\|aria\|alt" | head -20
        echo "=== PR branch index.html ==="
        cat _a11y_pr/out/index.html | grep -i "button\|img\|aria\|alt" | head -20
        echo "=== Are they identical? ==="
        diff _a11y_base/out/index.html _a11y_pr/out/index.html && echo "IDENTICAL" || echo "DIFFERENT"

    # ── 1. Checkout PR branch ─────────────────────────────────────────────────
    - name: Checkout PR branch
      uses: actions/checkout@v4
      with:
        path: _a11y_pr

    # ── 2. Checkout base (main) branch ───────────────────────────────────────
    - name: Checkout base branch
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.base.sha }}
        path: _a11y_base

    # ── 3. Setup Node ─────────────────────────────────────────────────────────
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20

    # ── 4. Install action's own dependencies ─────────────────────────────────
    - name: Install action dependencies
      shell: bash
      run: |
        cd ${{ github.action_path }}
        npm ci

    # ── 5. Install Playwright browser ────────────────────────────────────────
    - name: Install Playwright browser
      shell: bash
      run: |
        cd ${{ github.action_path }}
        npx playwright install chromium --with-deps

    # ── 6. Install & build PR branch ─────────────────────────────────────────
    - name: Install dependencies (PR branch)
      shell: bash
      run: |
        cd _a11y_pr/${{ inputs.APP_DIR }}
        npm ci

    - name: Build PR branch
      shell: bash
      run: |
        cd _a11y_pr/${{ inputs.APP_DIR }}
        npm run ${{ inputs.BUILD_COMMAND }}

    # ── 7. Install & build base branch ───────────────────────────────────────
    - name: Install dependencies (base branch)
      shell: bash
      run: |
        cd _a11y_base/${{ inputs.APP_DIR }}
        npm ci

    - name: Build base branch
      shell: bash
      run: |
        cd _a11y_base/${{ inputs.APP_DIR }}
        npm run ${{ inputs.BUILD_COMMAND }}

    # ── 8. Serve both builds ──────────────────────────────────────────────────
    # Wait for ports with tcp: so we only require the server to be listening,
    # not returning 2xx (Next.js static export may 404 on HEAD / until routes exist).
    - name: Serve both builds
      shell: bash
      run: |
        export PATH="${{ github.action_path }}/node_modules/.bin:$PATH"
        BASE_DIR="_a11y_base/${{ inputs.APP_DIR }}/${{ inputs.BUILD_DIR }}"
        PR_DIR="_a11y_pr/${{ inputs.APP_DIR }}/${{ inputs.BUILD_DIR }}"

        serve "$BASE_DIR" -l 4000 > /tmp/serve-4000.log 2>&1 &
        serve "$PR_DIR" -l 5000 > /tmp/serve-5000.log 2>&1 &

        echo "Waiting for servers to bind..."
        wait-on tcp:127.0.0.1:4000 --timeout 60000 \
          || (echo "Base branch server failed:" && cat /tmp/serve-4000.log && exit 1)
        wait-on tcp:127.0.0.1:5000 --timeout 60000 \
          || (echo "PR branch server failed:" && cat /tmp/serve-5000.log && exit 1)

        echo "Both servers ready."

    # ── 9. Scan base branch ───────────────────────────────────────────────────
    - name: Scan base branch
      shell: bash
      run: |
        node ${{ github.action_path }}/src/scan.js \
          --baseUrl http://localhost:4000 \
          --output /tmp/a11y_baseline.json \
          --urls "${{ inputs.URLS }}" \
          --ignore "${{ inputs.IGNORE_RULES }}" \
          --impactLevel "${{ inputs.IMPACT_LEVEL }}" \
          --waitForNetworkIdle "${{ inputs.WAIT_FOR_NETWORK_IDLE }}" \
          --extraWaitMs "${{ inputs.EXTRA_WAIT_MS }}"

    # ── 10. Scan PR branch ────────────────────────────────────────────────────
    - name: Scan PR branch
      shell: bash
      run: |
        node ${{ github.action_path }}/src/scan.js \
          --baseUrl http://localhost:5000 \
          --output /tmp/a11y_pr.json \
          --urls "${{ inputs.URLS }}" \
          --ignore "${{ inputs.IGNORE_RULES }}" \
          --impactLevel "${{ inputs.IMPACT_LEVEL }}" \
          --waitForNetworkIdle "${{ inputs.WAIT_FOR_NETWORK_IDLE }}" \
          --extraWaitMs "${{ inputs.EXTRA_WAIT_MS }}"

    # ── 11. Diff results ──────────────────────────────────────────────────────
    - name: Diff accessibility results
      shell: bash
      run: |
        node ${{ github.action_path }}/src/diff.js \
          --baseline /tmp/a11y_baseline.json \
          --head /tmp/a11y_pr.json \
          --output /tmp/a11y_diff.json || true

    # ── 12. Post PR comment ───────────────────────────────────────────────────
    - name: Post PR comment
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.TOKEN }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        FAIL_ON_REGRESSION: ${{ inputs.FAIL_ON_REGRESSION }}
      run: |
        node ${{ github.action_path }}/src/comment.js --diff /tmp/a11y_diff.json

    # ── 13. Upload scan artifacts for debugging ───────────────────────────────
    - name: Upload scan artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: a11y-diff-results
        path: |
          /tmp/a11y_baseline.json
          /tmp/a11y_pr.json
          /tmp/a11y_diff.json
        retention-days: 7
        if-no-files-found: ignore
